### ISSUE TITLE
Passing params between functions in series

### ISSUE THREAD

**Issue by cometbalan** [caolan/nimble#8]
I am using nimble in my application and its great to sequence how functions are executed.

But now i have a sitution in which i need to pass parameter from one function to other function
when running in "series".

Currently i am assigning any required value in global variable and using it, but i guess if there is a way to pass params between these functions, it would be wonderful.

Please suggest.

**Comment by caolan** [comment]
Using a variable outside of the 'series' call seems reasonable to me. It doesn't need to be global, it can just be from a closure.

**Comment by cometbalan** [comment]
Ok.
